# Generated by Django 6.0.3 on 2026-03-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "country", "verbose_name_plural": "countries"},
        ),
        migrations.AddField(
            model_name="club",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
